package ru.haritonenko.commonlibs.dto.kafka.event.type;

public enum NotificationEventType {
    BOOKING_CREATED,
    BOOKING_HOLD_CREATED,
    BOOKING_HOLD_EXPIRING,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_EXPIRED,
    BOOKING_CHECK_IN_REMINDER,
    BOOKING_FAILED,
    PAYMENT_INVOICE_CREATED,
    PAYMENT_PENDING,
    PAYMENT_CONFIRMED,
    PAYMENT_CANCELLED,
    PAYMENT_FAILED
}
