CREATE TABLE room_category
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name    INTEGER        NOT NULL DEFAULT 1,
    description  TEXT,
    max_guests   INTEGER        NOT NULL,
    price        NUMERIC(12, 2) NOT NULL,
    area_square  NUMERIC(12, 2) NOT NULL,
    total_units  INTEGER        NOT NULL,
    created_at   TIMESTAMPTZ    NOT NULL,
    updated_at   TIMESTAMPTZ    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_category_base_price
    ON room_category(price);

CREATE INDEX IF NOT EXISTS idx_category_max_guests
    ON room_category(max_guests);