CREATE TABLE room_category_photo
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_category_id  BIGINT         NOT NULL,
    path              VARCHAR(500)   NOT NULL,
    photo_type        INTEGER        NOT NULL,
    created_at        TIMESTAMPTZ    NOT NULL,
    updated_at        TIMESTAMPTZ    NOT NULL,

    CONSTRAINT fk_room_category_photo_category
        FOREIGN KEY (room_category_id)
            REFERENCES room_category(id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_room_category_photo_category_id
    ON room_category_photo(room_category_id);

CREATE INDEX IF NOT EXISTS idx_room_category_photo_type
    ON room_category_photo(photo_type);