create table service_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        INTEGER      NOT NULL UNIQUE DEFAULT 1,
    title       VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    is_active   BOOLEAN      NOT NULL,
    sort_order  INTEGER      NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);