INSERT INTO room_category_photo (
    room_category_id,
    path,
    photo_type,
    created_at,
    updated_at
) VALUES
      ((SELECT id FROM room_category WHERE type_name = 1 ORDER BY id DESC LIMIT 1), 'images/rooms/standard/4photo_main.png', 1, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 1 ORDER BY id DESC LIMIT 1), 'images/rooms/standard/1photo_default.png', 2, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 1 ORDER BY id DESC LIMIT 1), 'images/rooms/standard/2photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 1 ORDER BY id DESC LIMIT 1), 'images/rooms/standard/3photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 1 ORDER BY id DESC LIMIT 1), 'images/rooms/standard/5photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 1 ORDER BY id DESC LIMIT 1), 'images/rooms/standard/6photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 1 ORDER BY id DESC LIMIT 1), 'images/rooms/standard/7photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 1 ORDER BY id DESC LIMIT 1), 'images/rooms/standard/8photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 1 ORDER BY id DESC LIMIT 1), 'images/rooms/standard/9photo.png', 3, NOW(), NOW()),

      ((SELECT id FROM room_category WHERE type_name = 2 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_double/1photo_main.png', 1, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 2 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_double/2photo_default.png', 2, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 2 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_double/3photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 2 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_double/4photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 2 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_double/5photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 2 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_double/6photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 2 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_double/7photo.png', 3, NOW(), NOW()),

      ((SELECT id FROM room_category WHERE type_name = 3 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_plus/4photo_main.png', 1, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 3 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_plus/2photo_default.png', 2, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 3 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_plus/1photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 3 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_plus/3photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 3 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_plus/5photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 3 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_plus/6photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 3 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_plus/7photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 3 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_plus/8photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 3 ORDER BY id DESC LIMIT 1), 'images/rooms/standard_plus/9photo.png', 3, NOW(), NOW()),

      ((SELECT id FROM room_category WHERE type_name = 4 ORDER BY id DESC LIMIT 1), 'images/rooms/studio/1photo_main.png', 1, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 4 ORDER BY id DESC LIMIT 1), 'images/rooms/studio/3photo_default.png', 2, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 4 ORDER BY id DESC LIMIT 1), 'images/rooms/studio/2photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 4 ORDER BY id DESC LIMIT 1), 'images/rooms/studio/4photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 4 ORDER BY id DESC LIMIT 1), 'images/rooms/studio/5photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 4 ORDER BY id DESC LIMIT 1), 'images/rooms/studio/6photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 4 ORDER BY id DESC LIMIT 1), 'images/rooms/studio/7photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 4 ORDER BY id DESC LIMIT 1), 'images/rooms/studio/8photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 4 ORDER BY id DESC LIMIT 1), 'images/rooms/studio/9photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 4 ORDER BY id DESC LIMIT 1), 'images/rooms/studio/10photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 4 ORDER BY id DESC LIMIT 1), 'images/rooms/studio/11photo.png', 3, NOW(), NOW()),

      ((SELECT id FROM room_category WHERE type_name = 5 ORDER BY id DESC LIMIT 1), 'images/rooms/business_studio/1photo_main.png', 1, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 5 ORDER BY id DESC LIMIT 1), 'images/rooms/business_studio/3photo_default.png', 2, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 5 ORDER BY id DESC LIMIT 1), 'images/rooms/business_studio/2photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 5 ORDER BY id DESC LIMIT 1), 'images/rooms/business_studio/4photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 5 ORDER BY id DESC LIMIT 1), 'images/rooms/business_studio/5photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 5 ORDER BY id DESC LIMIT 1), 'images/rooms/business_studio/6photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 5 ORDER BY id DESC LIMIT 1), 'images/rooms/business_studio/7photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 5 ORDER BY id DESC LIMIT 1), 'images/rooms/business_studio/8photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 5 ORDER BY id DESC LIMIT 1), 'images/rooms/business_studio/9photo.png', 3, NOW(), NOW()),

      ((SELECT id FROM room_category WHERE type_name = 6 ORDER BY id DESC LIMIT 1), 'images/rooms/economy/2photo_main.png', 1, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 6 ORDER BY id DESC LIMIT 1), 'images/rooms/economy/1photo_default.png', 2, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 6 ORDER BY id DESC LIMIT 1), 'images/rooms/economy/3photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 6 ORDER BY id DESC LIMIT 1), 'images/rooms/economy/4photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 6 ORDER BY id DESC LIMIT 1), 'images/rooms/economy/5photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 6 ORDER BY id DESC LIMIT 1), 'images/rooms/economy/6photo.png', 3, NOW(), NOW()),
      ((SELECT id FROM room_category WHERE type_name = 6 ORDER BY id DESC LIMIT 1), 'images/rooms/economy/7photo.png', 3, NOW(), NOW());