spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5435/user_db}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    hikari:
      initialization-fail-timeout: ${USER_DB_INITIALIZATION_FAIL_TIMEOUT:-1}
      connection-timeout: ${USER_DB_CONNECTION_TIMEOUT:60000}
      validation-timeout: ${USER_DB_VALIDATION_TIMEOUT:10000}
      max-lifetime: ${USER_DB_MAX_LIFETIME:1800000}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

server:
  port: ${USER_SERVER_PORT:8083}

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
    path: ${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

openapi:
  title: River Park User Service API
  description: "User API for River Park: registration, authentication and profile."
  version: 1.0.0
  security-scheme-name: bearerAuth

jwt:
  secret-key: ${JWT_SECRET_KEY}
  lifetime: ${JWT_LIFETIME:86400000}

logging:
  level:
    ru.haritonenko.userservice: ${LOGGING_LEVEL_RU_HARITONENKO_USERSERVICE:INFO}
