package ru.haritonenko.telegrambot.bot.state;

public enum ChatStateType {
    IDLE,
    WAITING_ROOM_ID,
    WAITING_SERVICE_ID,
    WAITING_SERVICE_TYPE,
    WAITING_FILTER_GUESTS,
    WAITING_FILTER_CHECK_IN,
    WAITING_FILTER_CHECK_OUT,
    WAITING_FILTER_ROOM_TYPE,
    WAITING_FILTER_PRICE_FROM,
    WAITING_FILTER_PRICE_TO,
    WAITING_FILTER_MIN_AREA,
    WAITING_BOOKING_CHECK_IN,
    WAITING_BOOKING_CHECK_OUT,
    WAITING_BOOKING_ADULTS,
    WAITING_BOOKING_CHILDREN,
    WAITING_BOOKING_PROMO
}
