services:
  booking-postgres:
    image: postgres:16
    container_name: booking-postgres
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: ${BOOKING_DB_USERNAME}
      POSTGRES_PASSWORD: ${BOOKING_DB_PASSWORD}
      POSTGRES_DB: booking_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka:
    image: bitnami/kafka:3.8
    container_name: booking-kafka
    restart: unless-stopped
    ports:
      - "${KAFKA_HOST_PORT:-9094}:9094"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:${KAFKA_HOST_PORT:-9094}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_KRAFT_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      ALLOW_PLAINTEXT_LISTENER: yes
    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 20s


  booking-service:
    build:
      context: ..
      dockerfile: booking-service/Dockerfile
    container_name: booking-service
    restart: unless-stopped
    depends_on:
      booking-postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "${BOOKING_SERVER_PORT:-8084}:8084"
    environment:
      BOOKING_DB_URL: jdbc:postgresql://booking-postgres:5432/booking_db
      BOOKING_DB_USERNAME: ${BOOKING_DB_USERNAME}
      BOOKING_DB_PASSWORD: ${BOOKING_DB_PASSWORD}
      BOOKING_SERVER_PORT: 8084
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_LIFETIME: ${JWT_LIFETIME:-86400000}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BOOKING_EVENTS_TOPIC: ${BOOKING_EVENTS_TOPIC:-bookings-topic}
      PAYMENT_EVENTS_TOPIC: ${PAYMENT_EVENTS_TOPIC:-payments-topic}
      NOTIFICATION_EVENTS_TOPIC: ${NOTIFICATION_EVENTS_TOPIC:-notifications-topic}
      USER_SERVICE_BASE_URL: http://host.docker.internal:8083
      CATALOG_SERVICE_BASE_URL: http://host.docker.internal:8085
